security:
    encoders:
        Symfony\Component\Security\Core\User\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:
                class:    Morzan\TutorialBundle\Entity\User
                property: email
        admin:
            entity:
                class:    Morzan\TutorialBundle\Entity\AdminUser
                property: username
                
    firewalls:
#        profiler:
#            pattern:  ^/_profiler
#            security: false
#
#        wdt:
#            pattern:  ^/_wdt
#            security: false
#
#        login:
#            pattern:  ^/demo/secured/login$
#            security: false
        admin_area:
            pattern: ^/admin
            provider: admin
            http_basic:
                realm: "Administrator Area"
            stateless: true

        user_area:
            pattern:    .*
            provider: main
            form_login:
                check_path: /user/login_check
                login_path: /login
            logout:
                path:   /user/logout
                target: /
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: /admin.*, roles: ROLE_ADMIN }
        - { path: /user.*, roles: ROLE_USER }
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
