assetic:
    assets:
        app_js:
            inputs:
                - "@TutorialBundle/Resources/js/jquery.js"

        app_style:
            inputs:
                - "@TutorialBundle/Resources/scss/style.scss"
            filters: scss