assetic:
    assets:
        app_js:
            inputs:
                - "@TutorialBundle/Resources/js/jquery.js"
        admin_js:
            inputs:
                - "@app_js"
                - "@TutorialBundle/Resources/js/admin/product.js"
                - "@TutorialBundle/Resources/js/admin/order.js"
        app_style:
            inputs:
                - "@TutorialBundle/Resources/scss/style.scss"
            filters: scss