tutorial_default:
    resource: "@TutorialBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

tutorial_product:
    resource: "@TutorialBundle/Controller/ProductController.php"
    type:     annotation
    prefix:   /product

tutorial_user:
    resource: "@TutorialBundle/Controller/UserController.php"
    type:     annotation
    prefix:   /user

tutorial_admin:
    resource: "@TutorialBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

tutorial_order:
    resource: "@TutorialBundle/Controller/OrderController.php"
    type:     annotation
    prefix:   /order
