parameters:
    tutorial.lastviewed.class: Ckluster\TutorialBundle\Util\LastViewedManager
    tutorial.cookie_variation_registry.class: Ckluster\TutorialBundle\Util\CookieVariationRegistry
    tutorial.lastviewed.limit: 5
    tutorial.lastviewed.cookie.name: lastViewed
    # 2 years
    tutorial.lastviewed.cookie.expiretime: 63072000
    tutorial.shopping_cart.factory.class: Ckluster\TutorialBundle\Util\ShoppingCart\ShoppingCartManagerFactory
    tutorial.shopping_cart.class: Ckluster\TutorialBundle\Util\ShoppingCart\AbstractShoppingCartManager
    tutorial.shopping_cart.anonymous.class: Ckluster\TutorialBundle\Util\ShoppingCart\AnonymousShoppingCartManager

services:
    tutorial.lastviewed:
        class: %tutorial.lastviewed.class%
        scope: request
        calls:
            - [setEntityManager, [ "@doctrine" ]]
            - [setRequest, [ "@request" ]]
            - [setCookieRegistry, [ "@tutorial.cookie_variation_registry" ]]
        arguments:
            - %tutorial.lastviewed.limit%
            - %tutorial.lastviewed.cookie.name%
            - %tutorial.lastviewed.cookie.expiretime%

    tutorial.cookie_variation_registry:
        class: %tutorial.cookie_variation_registry.class%
        public: false
        arguments: ["@event_dispatcher"]
        
    tuturial.shopping_cart.factory:
        class: %tutorial.shopping_cart.factory.class%

    tutorial.shopping_cart:
        class: %tutorial.shopping_cart.class%
        factory_service: tuturial.shopping_cart.factory
        scope: request
        factory_method: get
        arguments:
            - "@security.context"
            - "@request"
            - "@doctrine"
            - "@tutorial.cookie_variation_registry"

    tutorial.shopping_cart.anonymous:
        class: %tutorial.shopping_cart.anonymous.class%
        parent: tutorial.shopping_cart
        scope: request
        arguments:
            - "@security.context"
            - "@request"
            - "@doctrine"
            - "@tutorial.cookie_variation_registry"
            - true





